### ISSUE TITLE
AFAD ACİL İ KULLANMAYI ÖNERİN

### ISSUE THREAD

**Issue by ghost** [acikkaynak/deprem-yardim-map-iframe#2]
Arkadaşlar her fırsatta insanlara Afad acil'i kullanmayı önerelim, başına buyrukluk, iletişim, ulaşım ve güvenliğimize karşı satürasyon saldırısı niteliği taşıyor.

**Comment by fdemir** [comment]
hemen

**Comment by fdemir** [comment]
eklendi.
